[tox]
env_list =
    py313
    lint
    build
    fmt
minversion = 4.24.1

[testenv]
description = run the tests with pytest
package = wheel
wheel_build_env = .pkg
deps =
    pytest>=8.3.4
    pytest-mock
    pytest-cov
commands =
    pytest {tty:--color=yes} --cov=resumaker {posargs}

[testenv:lint]
description = lint with flake8
deps = 
    flake8>=7.1.0
skip_install = true
commands =
    flake8 src

[testenv:build]
description = build project
deps = hatch
commands = 
    hatch build

[testenv:fmt]
description = format project
deps = 
    black
commands = 
    black src/
    black tests/

[flake8]
per-file-ignores = 
  src/resumaker/__init__.py: F401
max-line-length = 88
